- hosts: sap
  vars:
    ansible_user: "{{ lookup('ini','remote_ssh_user section=SAP file={{ filepath }}') }}"
  roles:
    - role: copy_exp_ctl

- hosts: all
  vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: export_system_tables

